services:
  backend:
    build: .
    container_name: dls-backend
    restart: always
    networks:
      - dls-network
    volumes:
      - ./logs:/app/logs
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    env_file:
    - .env

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: DLS
      MYSQL_ROOT_PASSWORD: TMNNT012928637160822863716
    ports:
      - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - dls-network

  seaweed-master:
    image: chrislusf/seaweedfs
    container_name: seaweed-master
    command: master -ip=seaweed-master -port=9333
    ports:
      - "9333:9333"
    networks:
    - dls-network

  seaweed-volume:
    image: chrislusf/seaweedfs
    container_name: seaweed-volume
    command: >
      volume
      -mserver="seaweed-master:9333"
      -port=8080
      -publicUrl=seaweed.hikarimoon.pro:8080
    ports:
      - "8080:8080"
    depends_on:
      - seaweed-master
    volumes:
      - volume_data:/data
    networks:
    - dls-network

  seaweed-filer:
    image: chrislusf/seaweedfs
    container_name: seaweed-filer
    command: filer -master="seaweed-master:9333"
    ports:
      - "8888:8888"
    depends_on:
      - seaweed-master
    networks:
    - dls-network

volumes:
  mysql_data:
  volume_data:

networks:
  dls-network:
    driver: bridge
