services:
  # backend:
  #   image: dls-backend
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DLS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: TMNNT012928637160822863716
  #     SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:8080"

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: DLS
      MYSQL_ROOT_PASSWORD: TMNNT012928637160822863716
    ports:
      - "3306:3306"

  seaweed-master:
    image: chrislusf/seaweedfs
    container_name: seaweed-master
    command: master -ip=seaweed-master -port=9333
    ports:
      - "9333:9333"

  seaweed-volume:
    image: chrislusf/seaweedfs
    container_name: seaweed-volume
    command: >
      volume
      -mserver="seaweed-master:9333"
      -port=8080
      -publicUrl=seaweed.hikarimoon.pro:8080
    ports:
      - "8080:8080"
    depends_on:
      - seaweed-master
    volumes:
      - volume_data:/data

  seaweed-filer:
    image: chrislusf/seaweedfs
    container_name: seaweed-filer
    command: filer -master="seaweed-master:9333"
    ports:
      - "8888:8888"
    depends_on:
      - seaweed-master

volumes:
  mysql_data:
  volume_data:
