spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: DLS

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET:default-dev-secret}
  expiration: 3600000
