spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: DLS

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET:default-dev-secret}
  expiration: 3600000

seaweedfs:
  master:
    # url: https://master-seaweed.hikarimoon.pro
    url: http://localhost:9333
  filer:
    # url: https://filer-seaweed.hikarimoon.pro
    url: http://localhost:8888