server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: DLS
  datasource:
    url: "jdbc:mysql://mysql:3306/DLS?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000        # 10 min
      max-lifetime: 1800000       # 30 min
      connection-timeout: 30000   # 30s

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

seaweedfs:
  master:
    url: http://seaweed-master:9333
  filer:
    url: http://seaweed-filer:8888